using DatabaseApp.Data;
using DatabaseApp.Data.DataModels;
using Microsoft.Office.Interop.Excel;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace DatabaseApp
{
    /// <summary>
    /// Interaction logic for AccountOrder.xaml
    /// </summary>
    public partial class AccountOrder : System.Windows.Window
    {
        SqlConnection con = new SqlConnection("Server=.;Database=dbdemo;Trusted_Connection=SSPI;MultipleActiveResultSets=true;TrustServerCertificate=true");
        List<Customer> customers = new List<Customer>();
        List<CustomerOrder> customerOrders = new List<CustomerOrder>();
        public static string index;
        public static string currentStatus;
        public static string currentInputName;
        public static DateTime currentDate;
        public string status;
        public string action;
        public string query;

        public AccountOrder()
        {
            InitializeComponent();
            txtTitle.Text = $"List of {Login.passText} orders";
            LoadOrder();
            //cbFilter.Text = "All";
        }

        void LoadOrder()
        {
            var db = new CustomerDb();
            customers = db.Customers.ToList();
            dgInvoice.ItemsSource = customers;
        }

        public void ActivityLog()
        {
            con.Open();
            string currentdatetime = System.DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            string query = "INSERT INTO ActivityLog VALUES ('" + Login.GetID + "','" + Login.passText + "','" + Login.GetRole + "','" + action + "', '" + "Checkout status" + "', '" + currentdatetime + "')"; ;
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.ExecuteNonQuery();
            con.Close();
        }

        void CancelOrder()
        {
            con.Open();
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@CustomerID", index);
            cmd.Parameters.AddWithValue("@PaymentStatus", status);
            cmd.ExecuteNonQuery();
            con.Close();
        }

        private void DataGridRow_Selected(object sender, RoutedEventArgs e)
        {
            var row = sender as DataGridRow;
            var acc = row.DataContext as Customer;

            index = acc.CustomerID;
            currentInputName = acc.InputName;
            currentDate = acc.CreatedDate;
        }

        private void dgInvoice_AutoGeneratedColumns(object sender, EventArgs e)
        {
            ShowResult();
        }

        void Refresh()
        {
            new AccountOrder().Show();
            this.Close();
        }

        private void cbFilter_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            LoadOrder();
            switch (cbFilter.SelectedIndex.ToString())
            {
                case "0":
                    ShowResult();
                    break;
                case "1":
                    Ongoing();
                    break;
                case "2":
                    Completed();
                    break;
                case "3":
                    Canceled();
                    break;
            }
        }

        void ShowResult()
        {
            dgInvoice.Columns[0].Visibility = Visibility.Hidden;
            dgInvoice.Columns[1].Visibility = Visibility.Hidden;
            dgInvoice.Columns[2].Visibility = Visibility.Hidden;
            dgInvoice.Columns[3].Visibility = Visibility.Hidden;
            dgInvoice.Columns[4].Visibility = Visibility.Hidden;
            dgInvoice.Columns[6].Visibility = Visibility.Hidden;
            dgInvoice.Columns[7].Visibility = Visibility.Hidden;
            dgInvoice.Columns[8].Visibility = Visibility.Hidden;
            dgInvoice.Columns[9].Visibility = Visibility.Hidden;
            dgInvoice.Columns[10].Visibility = Visibility.Hidden;
            dgInvoice.Columns[11].Visibility = Visibility.Hidden;
            dgInvoice.Columns[12].Visibility = Visibility.Hidden;
            dgInvoice.Columns[13].Visibility = Visibility.Hidden;
            dgInvoice.Columns[14].Visibility = Visibility.Hidden;
            dgInvoice.Columns[15].Visibility = Visibility.Hidden;

            customers.RemoveAll(x => x.AccountID != Login.GetID);
        }

        void Ongoing()
        {
            ShowResult();
            customerOrders.RemoveAll(x => x.OrderStatus == "Stage 4");
            customers.RemoveAll(x => x.PaymentStatus != "Payment incomplete");
        }

        void Completed()
        {
            ShowResult();
            customerOrders.RemoveAll(x => x.OrderStatus != "Stage 4");
            customers.RemoveAll(x => x.PaymentStatus != "Payment complete");
        }

        void Canceled()
        {
            ShowResult();
            customers.RemoveAll(x => x.PaymentStatus != "Order cancel");
        }

        private void btnRefresh_Click(object sender, RoutedEventArgs e)
        {
            Refresh();
        }

        private void btnOderDetail_Click(object sender, RoutedEventArgs e)
        {
            if (index != null)
            {
                OrderDetail oderDetail = new OrderDetail(this);
                Opacity = 0.2;
                oderDetail.ShowDialog();
                Opacity = 1;
                Refresh();
            }
            else
            {
                System.Windows.MessageBox.Show("Select an invoice first", "Error");
            }
        }

        private void btnProductsDetail_Click(object sender, RoutedEventArgs e)
        {
            if (index != null)
            {
                OrderProductDetail orderProductDetail = new OrderProductDetail(this);
                Opacity = 0.2;
                orderProductDetail.ShowDialog();
                Opacity = 1;
                Refresh();
            }
            else
            {
                System.Windows.MessageBox.Show("Select an invoice first", "Error");
            }
        }

        private void btnOderStatus_Click(object sender, RoutedEventArgs e)
        {
            OrderStatus orderStatus = new OrderStatus(this);
            Opacity = 0.2;
            orderStatus.ShowDialog();
            Opacity = 1;
            Refresh();
        }

        private void btnCancelOder_Click(object sender, RoutedEventArgs e)
        {
            status = "Order cancel";
            action = $" Order {index} canceled";

            if (currentStatus != "Order cancel")
            {
                var result = System.Windows.MessageBox.Show("This action is permanent, are you sure?", "Warning", (MessageBoxButton)MessageBoxButtons.YesNo, (MessageBoxImage)MessageBoxIcon.Warning);
                if (result == MessageBoxResult.Yes)
                {
                    query = "UPDATE Customer SET PaymentStatus = @PaymentStatus WHERE CustomerID = @CustomerID";
                    CancelOrder();
                    query = "UPDATE CustomerOrder SET PaymentStatus = @PaymentStatus WHERE CustomerID = @CustomerID";
                    CancelOrder();

                    ActivityLog();
                    System.Windows.MessageBox.Show("Order cancel", "Notification");
                    index = null;
                    Refresh();
                }
            }
            else
            {
                System.Windows.MessageBox.Show("Order already canceled", "Error");
                index = null;
                LoadOrder();
            }
        }
    }
}
