using DatabaseApp.Data;
using DatabaseApp.Data.DataModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace DatabaseApp
{
    /// <summary>
    /// Interaction logic for OrderManagement.xaml
    /// </summary>
    public partial class OrderManagement : Window
    {
        SqlConnection con = new SqlConnection("Server=.;Database=dbdemo;Trusted_Connection=SSPI;MultipleActiveResultSets=true;TrustServerCertificate=true");
        List<CustomerOrder> customerOrders = new List<CustomerOrder>();

        public static string index;
        public static string stage;

        public OrderManagement()
        {
            InitializeComponent();
            GetOrder();
        }

        void GetOrder()
        {
            var db = new CustomerOrderDb();
            customerOrders = db.CustomerOrders.ToList();
            dgOrder.ItemsSource = customerOrders;
        }

        void ReadOrder()
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("SELECT * FROM Customer WHERE @CustomerID = CustomerID", con);
            cmd.Parameters.AddWithValue("@CustomerID", index);
            SqlDataReader da = cmd.ExecuteReader();
            while (da.Read())
            {
                txtPaymentMethod.Text = da.GetValue(16).ToString();
            }
            con.Close();

            con.Open();
            cmd = new SqlCommand("SELECT * FROM CustomerOrder WHERE @CustomerID = CustomerID", con);
            cmd.Parameters.AddWithValue("@CustomerID", index);
            da = cmd.ExecuteReader();
            while (da.Read())
            {
                txtName.Text = da.GetValue(2).ToString();
                txtStatus.Text = da.GetValue(3).ToString();
                txtStage.Text = da.GetValue(4).ToString();
            }
            con.Close();
        }

        private void DataGridRow_Selected(object sender, RoutedEventArgs e)
        {
            var row = sender as DataGridRow;
            var acc = row.DataContext as CustomerOrder;

            index = acc.CustomerID;
            stage = acc.OrderStatus;
            ReadOrder();
        }

        private void dgOrder_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgOrder.Columns[3].Visibility = Visibility.Hidden;
        }

        private void cbStage_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            GetOrder();
            switch (cbStage.SelectedIndex.ToString())
            {
                case "0":
                    cbStage.Text = "Full";
                    break;
                case "1":
                    cbStage.Text = "Stage 0";
                    customerOrders.RemoveAll(x => x.OrderStatus != "Stage 0");
                    break;
                case "2":
                    cbStage.Text = "Stage 1";
                    customerOrders.RemoveAll(x => x.OrderStatus != "Stage 1");
                    break;
                case "3":
                    cbStage.Text = "Stage 2";
                    customerOrders.RemoveAll(x => x.OrderStatus != "Stage 2");
                    break;
                case "4":
                    cbStage.Text = "Stage 3";
                    customerOrders.RemoveAll(x => x.OrderStatus != "Stage 3");
                    break;
                case "5":
                    cbStage.Text = "Stage 4";
                    customerOrders.RemoveAll(x => x.OrderStatus != "Stage 4");
                    break;
            }
        }

        void Refresh()
        {
            index = null;
            new OrderManagement().Show();
            this.Close();
        }

        private void btnRefresh_Click(object sender, RoutedEventArgs e)
        {
            Refresh();
        }

        private void btnDetail_Click(object sender, RoutedEventArgs e)
        {
            OrderManagementDetail orderManagementDetail = new OrderManagementDetail(this);
            Opacity = 0.2;
            orderManagementDetail.ShowDialog();
            Opacity = 1;
            Refresh();
        }

        private void btnUpdate_Click(object sender, RoutedEventArgs e)
        {
            OrderManagementUpdate orderManagementUpdate = new OrderManagementUpdate(this);
            Opacity = 0.2;
            orderManagementUpdate.ShowDialog();
            Opacity = 1;
            Refresh();
        }
    }
}
